export const LOAD_PIZZAS_REQUEST = "LOAD_PIZZAS_REQUEST";
export const LOAD_PIZZAS_SUCCESS = "LOAD_PIZZAS_SUCCESS";
export const LOAD_PIZZAS_FAILED = "LOAD_PIZZAS_FAILED";

export const ADD_TO_CART = "ADD_TO_CART";